name: Build & Deploy HiveMind

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  IMAGE_BASE: gcr.io/${{ secrets.PROJECT_ID }}/hivemind-api

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/CommunicationControl
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set variables for branch and commit
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SHORT_SHA=${GITHUB_SHA::7}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.hivemind -t ${{ env.IMAGE_BASE }}:${BRANCH_NAME}-${SHORT_SHA} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_BASE }}:${BRANCH_NAME}-${SHORT_SHA}
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone us-central1-c --project ${{ secrets.PROJECT_ID }}

      - name: Set image in hive-mind deployment
        run: |
          kubectl config set-context --current --namespace=${BRANCH_NAME}
          kubectl set image deployment/hivemind-api hivemind-api=${{ env.IMAGE_BASE }}:${BRANCH_NAME}-${SHORT_SHA}