apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemind-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemind-api
  template:
    metadata:
      labels:
        app: hivemind-api
    spec:
      containers:
        - name: hivemind-api
          image: gcr.io/angelic-tracer-455316-q7/hivemind-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5149
          env:
            - name: CommunicationConfiguration__CommunicationControlIP
              value: communication-control
            - name: CommunicationConfiguration__CommunicationControlPath
              value: communication/api/v1/hive
            - name: CommunicationConfiguration__CommunicationControlPort
              value: "80"
      restartPolicy: Always
      